"""third commit addin fake_addr col in address table

Revision ID: efc9a414273e
Revises: 3db9d15a6749
Create Date: 2022-05-25 18:56:34.270817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc9a414273e'
down_revision = '3db9d15a6749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('fake_addr', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'fake_addr')
    # ### end Alembic commands ###
